const Student = require('./Student')
const Stack = require('./Stack')

const stack = new Stack()
console.log(stack)
const s1 = new Student('Mike', 18)
const s2 = new Student('Jerry', 19)
const s3 = new Student('Tom', 17)
stack.push(s1)
stack.push(s2)
stack.push(s3)
// console.log(stack)
// stack.pop()
// console.log(stack)
// console.log(stack.peek())
// console.log(stack.getCapacity(), stack.getSize())
console.log(stack.toString())
